//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Core.DB.REDCHEETAH.STAGING
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceCode
    {
        public int DeviceCodesId { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public int Code { get; set; }
        public string MobileNumber { get; set; }
        public System.DateTime Created { get; set; }
    }
}
