//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Core.DB.REDCHEETAH.STAGING
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeviceInfo()
        {
            this.DeviceConnects = new HashSet<DeviceConnect>();
            this.DeviceLocations = new HashSet<DeviceLocation>();
            this.MessageReads = new HashSet<MessageRead>();
            this.Messages = new HashSet<Message>();
        }
    
        public int DeviceId { get; set; }
        public int SwiftId { get; set; }
        public int AgeRange { get; set; }
        public int Gender { get; set; }
        public string HardwareId { get; set; }
        public int Platform { get; set; }
        public string Version { get; set; }
        public int FormFactor { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastModified { get; set; }
        public Nullable<bool> MarkedForDeletion { get; set; }
        public Nullable<System.DateTime> MarkedDeletedDate { get; set; }
        public bool Status { get; set; }
        public System.DateTime LastTimeActive { get; set; }
        public Nullable<int> LastMessageId { get; set; }
        public Nullable<System.DateTime> LastMessageDate { get; set; }
        public Nullable<int> LastConnectId { get; set; }
        public string CityOfResidence { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public int InfoType { get; set; }
        public string IPAddress { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string MacAddress { get; set; }
        public int ConnectedTo { get; set; }
        public string NotificationID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceConnect> DeviceConnects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceLocation> DeviceLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessageRead> MessageReads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
    }
}
