//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Core.DB.REDCHEETAH.STAGING
{
    using System;
    using System.Collections.Generic;
    
    public partial class RC_CHANNELS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RC_CHANNELS()
        {
            this.RC_LOCATIONS = new HashSet<RC_LOCATIONS>();
        }
    
        public int CHANNEL_ID { get; set; }
        public string CHANNEL_NAME { get; set; }
        public int SECTOR_ID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual RC_SECTORS RC_SECTORS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RC_LOCATIONS> RC_LOCATIONS { get; set; }
    }
}
