//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Core.DB.REDCHEETAH.STAGING
{
    using System;
    using System.Collections.Generic;
    
    public partial class RC_LOCATIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RC_LOCATIONS()
        {
            this.RC_MODEMS = new HashSet<RC_MODEMS>();
        }
    
        public int LOCATION_ID { get; set; }
        public string LOCATION_NAME { get; set; }
        public int CHANNEL_ID { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual RC_CHANNELS RC_CHANNELS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RC_MODEMS> RC_MODEMS { get; set; }
    }
}
