//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Core.DB.REDCHEETAH.STAGING
{
    using System;
    using System.Collections.Generic;
    
    public partial class RC_Sessions
    {
        public int SessionId { get; set; }
        public string DeviceIMEI { get; set; }
        public string AccessPointIPAddress { get; set; }
        public string VPNIPAddress { get; set; }
        public System.DateTime SessionStartTime { get; set; }
        public Nullable<System.DateTime> SessionEndTime { get; set; }
    }
}
