//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Core.DB.REDCHEETAH.STAGING
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCRegisteredDevice
    {
        public int deviceId { get; set; }
        public string macAddress { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string phoneNumber { get; set; }
        public string gender { get; set; }
        public string ageRange { get; set; }
        public System.DateTime creationDate { get; set; }
        public string email { get; set; }
        public int regStatus { get; set; }
        public string remarks { get; set; }
        public string agentCode { get; set; }
    }
}
