//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Core.DB.REDCHEETAH.STAGING
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedCheetahVerification
    {
        public int Id { get; set; }
        public string Guid { get; set; }
        public string VerificationCode { get; set; }
        public string PhoneNo { get; set; }
        public string TimeStamp { get; set; }
        public string VerificationStatus { get; set; }
    }
}
