//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Core.DB.REDCHEETAH.STAGING
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedCheetahUser
    {
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string IpAddress { get; set; }
        public bool Enable { get; set; }
        public bool AddedToRadius { get; set; }
        public bool DeleteUser { get; set; }
        public string MacAddress { get; set; }
        public bool IpAddressUpdated { get; set; }
    }
}
