//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Core.DB.REDCHEETAH.STAGING
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceParameter
    {
        public int ServiceId { get; set; }
        public string Name { get; set; }
        public int Frequency { get; set; }
        public int MinMessageTime { get; set; }
        public Nullable<int> MaxMessageTime { get; set; }
        public int MinLastMessageTime { get; set; }
        public string url { get; set; }
        public string url2 { get; set; }
    }
}
