//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPhone.Core.DB.REDCHEETAH.STAGING
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserToDisableOrEnable
    {
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public bool ShouldEnable { get; set; }
        public bool Processed { get; set; }
    }
}
